### ISSUE TITLE
Add(IBox) in world

### ISSUE THREAD

**Issue by MunWolf** [aloisdeniel/Humper#4]
I would like to have an Add(IBox) to add a box into the world as opposed to Create, this is mostly to remove a box from all collisions without having to recreate the IBox class when I want to add it again.

Cheers,
Richard

P.S. I would fix this use case by extending your World class but sadly the grid inside it is private not protected.

**Comment by CloneDeath** [comment]
This should be sufficient to meet any of your needs.
